### ISSUE TITLE
DatePicker errors when not given optional inital_date on creation.

### ISSUE THREAD

**Issue by K8sKween** [nicklambourne/slackblocks#66]
Problem:
DatePicker errors when calling _resolve is the optional variable `initial_date` is not given

Testing(This is nested inside a ModalView that renders perfectly when it is initialized with `initial_date` is provided):
I am just going to provide the part of the code that stands out
```
delete_after_block = InputBlock(
        label=Text("Delete After",type_=TextType.PLAINTEXT, emoji=True),
        element=DatePicker(
            action_id="datepicker-action",
            #set to current date plus 4 days as unix timestamp in second
            #initial_date = str(datetime.now().date() + timedelta(days=4)),
        ),
        block_id="delete_after_block"
    )
 ```
 Error:
 ```
 Failed to run listener function (error: 'DatePicker' object has no attribute 'initial_date')
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/opt/homebrew/lib/python3.11/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/victoriamann/Source/slack-workflow-server/platform-bot/src/main.py", line 49, in platform_bot_test
    view=modal_view.to_dict()
         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slackblocks/views.py", line 54, in to_dict
    return self._resolve()
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slackblocks/views.py", line 93, in _resolve
    modal_view = super()._resolve()
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slackblocks/views.py", line 44, in _resolve
    view["blocks"] = [block._resolve() for block in self.blocks]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slackblocks/views.py", line 44, in <listcomp>
    view["blocks"] = [block._resolve() for block in self.blocks]
                      ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slackblocks/blocks.py", line 269, in _resolve
    input_block["element"] = self.element._resolve()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/slackblocks/elements.py", line 180, in _resolve
    if self.initial_date:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DatePicker' object has no attribute 'initial_date'
```

When the line with the inital_date is uncommentated it works perfectly.

[Relevant documentation](https://api.slack.com/reference/block-kit/block-elements#datepicker)

`initial_date` is an optional field in the constructor and for the Slack API.

Possible fix: Update the `_resolve` method to omit the field when it is set to its default value of `None`

**Comment by K8sKween** [comment]
@nicklambourne I do plan on raising PRs for all the issues I have been opening, just wanted to raise the issue first if there was something obviously wrong with my usage.

**Comment by nicklambourne** [comment]
Hey @K8sKween, your usage looks fine to me, just an oversight on my part when putting it together, thanks for letting me know. Happy for any and all PRs, I will keep an eye out 👀

**Comment by nicklambourne** [comment]
I might push through fixes for these in the next day or so, unless you've already had a chance to get something together (in which case let me know and I'll hold off).

**Comment by K8sKween** [comment]
If you get time go ahead, I have been bogged down, great work on the documentation for the 1.0.0 release btw!
